#配置mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/management?useSSL=false&useUnicode=true&serverTimezone=GMT
    username: root
    password: 150
    # 使用阿里的Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
#配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml