server:
  port: 8083
spring:
  profiles:
    active: dev
  #配置mysql数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.205.75:3306/management?useSSL=false&useUnicode=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: 123456
# 使用阿里的Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource

#配置mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
# 配置逻辑删除
  global-config:
    db-config:
      logic-delete-field: is_deleted  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value:  0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
#枚举类的扫描包
  type-enums-package: com.example.management.entity

#配置日志：打印出SQL语句
logging:
  level:
    root: warn
    com.example.management.mapper: trace
  pattern:
    console: '%p%m%n'