package com.example.management.repository;

import com.example.management.entity.MemAffair;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

@Mapper
public interface MemAffairMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_affair
     *
     * @mbg.generated Sat Jul 18 11:00:36 CST 2020
     */
    @Update({
        "update  mem_affair",
        "set is_deleted= 1 ",
            "where id = #{id,jdbcType=BIGINT}"
    })
    boolean deleteByPrimaryKey(int id);

    @Update({
            "update mem_affair",
            "set is_deleted = 0",
            "where id = #{id,jdbcType=BIGINT}"
    })
    boolean UndeleteByPrimaryKey(int id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_affair
     *
     * @mbg.generated Sat Jul 18 11:00:36 CST 2020
     */
    @Insert({
        "insert into mem_affair (id, mem_id, ",
        "affair_id, is_deleted)",
        "values (#{id,jdbcType=BIGINT}, #{memId,jdbcType=BIGINT}, ",
        "#{affairId,jdbcType=BIGINT}, #{isDeleted,jdbcType=BIT})"
    })
    boolean insert(MemAffair record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_affair
     *
     * @mbg.generated Sat Jul 18 11:00:36 CST 2020
     */
    @Select({
        "select",
        "id, mem_id, affair_id, is_deleted",
        "from mem_affair",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="mem_id", property="memId", jdbcType=JdbcType.BIGINT),
        @Result(column="affair_id", property="affairId", jdbcType=JdbcType.BIGINT),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    MemAffair selectByPrimaryKey(int id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_affair
     *
     * @mbg.generated Sat Jul 18 11:00:36 CST 2020
     */
    @Select({
        "select",
        "id, mem_id, affair_id, is_deleted",
        "from mem_affair"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="mem_id", property="memId", jdbcType=JdbcType.BIGINT),
        @Result(column="affair_id", property="affairId", jdbcType=JdbcType.BIGINT),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    List<MemAffair> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_affair
     *
     * @mbg.generated Sat Jul 18 11:00:36 CST 2020
     */
    @Update({
        "update mem_affair",
        "set mem_id = #{memId,jdbcType=BIGINT},",
          "affair_id = #{affairId,jdbcType=BIGINT},",
          "is_deleted = #{isDeleted,jdbcType=BIT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    boolean updateByPrimaryKey(MemAffair record);
}