package com.example.management.entity;

import java.util.Date;

public class Affair {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affair.id
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    private int id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affair.end_time
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affair.start_time
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affair.title
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affair.content
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affair.is_OK
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    private Boolean isOk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affair.type
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affair.is_deleted
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affair.id
     *
     * @return the value of affair.id
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    public int getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affair.id
     *
     * @param id the value for affair.id
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affair.end_time
     *
     * @return the value of affair.end_time
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affair.end_time
     *
     * @param endTime the value for affair.end_time
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affair.start_time
     *
     * @return the value of affair.start_time
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affair.start_time
     *
     * @param startTime the value for affair.start_time
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affair.title
     *
     * @return the value of affair.title
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affair.title
     *
     * @param title the value for affair.title
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affair.content
     *
     * @return the value of affair.content
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affair.content
     *
     * @param content the value for affair.content
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affair.is_OK
     *
     * @return the value of affair.is_OK
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    public Boolean getIsOk() {
        return isOk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affair.is_OK
     *
     * @param isOk the value for affair.is_OK
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    public void setIsOk(Boolean isOk) {
        this.isOk = isOk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affair.type
     *
     * @return the value of affair.type
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affair.type
     *
     * @param type the value for affair.type
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affair.is_deleted
     *
     * @return the value of affair.is_deleted
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affair.is_deleted
     *
     * @param isDeleted the value for affair.is_deleted
     *
     * @mbg.generated Fri Jul 17 19:04:15 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}