package com.example.management.entity;



public class Club  {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.id
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.name
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.logo
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.intro
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.username
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.password
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.is_deleted
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.id
     *
     * @return the value of club.id
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.id
     *
     * @param id the value for club.id
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.name
     *
     * @return the value of club.name
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.name
     *
     * @param name the value for club.name
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.logo
     *
     * @return the value of club.logo
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.logo
     *
     * @param logo the value for club.logo
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.intro
     *
     * @return the value of club.intro
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.intro
     *
     * @param intro the value for club.intro
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.username
     *
     * @return the value of club.username
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.username
     *
     * @param username the value for club.username
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.password
     *
     * @return the value of club.password
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.password
     *
     * @param password the value for club.password
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.is_deleted
     *
     * @return the value of club.is_deleted
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.is_deleted
     *
     * @param isDeleted the value for club.is_deleted
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}