package com.example.management.entity;



public class Mem  {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem.id
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem.name
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem.stuid
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    private String stuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem.password
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem.college
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    private String college;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem.major
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem.gender
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    private Boolean gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem.phone
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem.qq
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem.email
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem.dept_id
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    private Long deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem.is_deleted
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem.id
     *
     * @return the value of mem.id
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem.id
     *
     * @param id the value for mem.id
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem.name
     *
     * @return the value of mem.name
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem.name
     *
     * @param name the value for mem.name
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem.stuid
     *
     * @return the value of mem.stuid
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public String getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem.stuid
     *
     * @param stuid the value for mem.stuid
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public void setStuid(String stuid) {
        this.stuid = stuid == null ? null : stuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem.password
     *
     * @return the value of mem.password
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem.password
     *
     * @param password the value for mem.password
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem.college
     *
     * @return the value of mem.college
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem.college
     *
     * @param college the value for mem.college
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public void setCollege(String college) {
        this.college = college == null ? null : college.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem.major
     *
     * @return the value of mem.major
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem.major
     *
     * @param major the value for mem.major
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem.gender
     *
     * @return the value of mem.gender
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public Boolean getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem.gender
     *
     * @param gender the value for mem.gender
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem.phone
     *
     * @return the value of mem.phone
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem.phone
     *
     * @param phone the value for mem.phone
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem.qq
     *
     * @return the value of mem.qq
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem.qq
     *
     * @param qq the value for mem.qq
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem.email
     *
     * @return the value of mem.email
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem.email
     *
     * @param email the value for mem.email
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem.dept_id
     *
     * @return the value of mem.dept_id
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public Long getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem.dept_id
     *
     * @param deptId the value for mem.dept_id
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem.is_deleted
     *
     * @return the value of mem.is_deleted
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem.is_deleted
     *
     * @param isDeleted the value for mem.is_deleted
     *
     * @mbg.generated Fri Jul 17 18:55:40 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}